version: '3.6'
services:
  tester:
    container_name: tester
    restart: always
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./server:/sandbox
      - ./tests:/tests
