version: '3.6'
services:
  client:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "8080:80"
  server:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8888:8888"
